In [1]:
!pip install pandas-profiling==2.7.1

     |████████████████████████████████| 256kB 5.7MB/s 
     |████████████████████████████████| 81kB 7.0MB/s 
     |████████████████████████████████| 61kB 6.0MB/s 
     |████████████████████████████████| 3.2MB 13.2MB/s 
     |████████████████████████████████| 1.1MB 37.1MB/s 
     |████████████████████████████████| 296kB 48.1MB/s 
  Created wheel for phik: filename=phik-0.11.2-cp37-none-any.whl size=1107413 sha256=07fcbfb2cb8781ab05f0e755ad15759a6d80ef0db6df906fab98236171e9001f
  Stored in directory: /root/.cache/pip/wheels/c0/a3/b0/f27b1cfe32ea131a3715169132ff6d85653789e80e966c3bf6
  Created wheel for htmlmin: filename=htmlmin-0.1.12-cp37-none-any.whl size=27085 sha256=ffd014d5a394dcd94a006f8dab960bbfffaab42bb81b80bf5ea269b2f7897314
  Stored in directory: /root/.cache/pip/wheels/43/07/ac/7c5a9d708d65247ac1f94066cf1db075540b85716c30255459
Successfully built phik htmlmin
ERROR: phik 0.11.2 has requirement scipy>=1.5.2, but you'll have scipy 1.4.1 which is incompatible.
  Found existing in

In [2]:
from google.colab import drive
drive.mount("/content/gdrive")
%cd '/content/gdrive/MyDrive/LDS6_S7N_TranHoangBach/BaiTap/Chapter_4'

Mounted at /content/gdrive
/content/gdrive/MyDrive/LDS6_S7N_TranHoangBach/BaiTap/Chapter_4


In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
import pandas_profiling as pp
from sklearn.naive_bayes import BernoulliNB, MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

%matplotlib inline

In [7]:
text = [
        'ngay hom nay la ngay may',
        'toi mot gio rang chiu',
        'ong gia di nhanh qua',
]

count_vec = CountVectorizer()
count_vec.fit(text)
bag_of_words = count_vec.transform(text)
print(bag_of_words.toarray())

[[0 0 0 0 1 1 1 0 1 2 0 0 0 0 0]
 [1 0 0 1 0 0 0 1 0 0 0 0 0 1 1]
 [0 1 1 0 0 0 0 0 0 0 1 1 1 0 0]]


In [8]:
count_vec.vocabulary_

{'chiu': 0,
 'di': 1,
 'gia': 2,
 'gio': 3,
 'hom': 4,
 'la': 5,
 'may': 6,
 'mot': 7,
 'nay': 8,
 'ngay': 9,
 'nhanh': 10,
 'ong': 11,
 'qua': 12,
 'rang': 13,
 'toi': 14}

In [14]:
len(count_vec.vocabulary_.keys())

15

In [15]:
count_vec.vocabulary_.keys()

dict_keys(['ngay', 'hom', 'nay', 'la', 'may', 'toi', 'mot', 'gio', 'rang', 'chiu', 'ong', 'gia', 'di', 'nhanh', 'qua'])

In [26]:
X = np.array([["Red", "Sports", "Domestic"],
              ["Red", "Sports", "Domestic"], 
              ["Red", "Sports", "Domestic"], 
              ["Yellow", "Sports", "Domestic"], 
              ["Yellow", "Sports", "Imported"],
              ["Yellow", "SUV", "Imported"], 
              ["Yellow", "SUV", "Imported"], 
              ["Yellow", "SUV", "Domestic"],
              ["Red", "SUV", "Imported"], 
              ["Red", "Sports", "Imported"]])
y = np.array(["Yes", "No", "Yes", "No", "Yes", "No", "Yes", "No", "No", "Yes"])
X = pd.DataFrame(X, columns=['Color', 'Type', 'Origin'])
X = pd.get_dummies(X)
y = np.array(pd.get_dummies(y, drop_first=True)).flatten()
y

array([1, 0, 1, 0, 1, 0, 1, 0, 0, 1], dtype=uint8)

In [27]:
X

Color_Red  Color_Yellow  ...  Origin_Domestic  Origin_Imported
0          1             0  ...                1                0
1          1             0  ...                1                0
2          1             0  ...                1                0
3          0             1  ...                1                0
4          0             1  ...                0                1
5          0             1  ...                0                1
6          0             1  ...                0                1
7          0             1  ...                1                0
8          1             0  ...                0                1
9          1             0  ...                0                1

[10 rows x 6 columns]

In [28]:
model = BernoulliNB()
model.fit(X, y)
model.score(X, y)

0.8

In [33]:
X_test = [[0, 1, 0, 1, 0, 1]]
prediction = model.predict(X_test)[0]
print('Probability of Stolen: {:.4f}'.format(model.predict_proba(X_test)[0,1]))
print('Prediction: {}'.format('Stolen' if prediction==1 else 'Not stolen'))

Probability of Stolen: 0.7353
Prediction: Stolen


In [34]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X, y)
model.score(X, y)
X_test = [[0, 1, 0, 1, 0, 1]]
prediction = model.predict(X_test)[0]
print('Probability of Stolen: {:.4f}'.format(model.predict_proba(X_test)[0,1]))
print('Prediction: {}'.format('Stolen' if prediction==1 else 'Not stolen'))

Probability of Stolen: 0.8396
Prediction: Stolen


In [35]:
import pickle
pkl_filename = 'model.pkl'
with open(pkl_filename, 'wb') as file:
    pickle.dump(model, file)

In [36]:
with open(pkl_filename, 'rb') as file:
    saved_model = pickle.load(file)